name: Pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: Download Assets
        run: './gradlew downloadAssets'
      - name: Generate Sources
        run: './gradlew genSources'
      - name: Build with Gradle
        run: './gradlew build'
      - name: Get version
        run: 'version=$(./gradlew -q getVersionName)'
      - name: Get commit hash
        run: 'commithash=$(echo $GITHUB_SHA | head -c 12)'
      - name: Set Release Note Version
        run: 'sed -i "s/{{ VERSION }}/$version/" RELEASE_NOTE.md'
      - name: Set Release Note Commit Hash
        run: 'sed -i "s/{{ COMMIT_HASH }}/$commithash/" RELEASE_NOTE.md'
      - name: Set Release Note Message
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{ COMMIT_MESSAGE }}"
          replace: ${{ github.event.head_commit.message }}
          include: 'RELEASE_NOTE.md'
          regex: false
      - name: Rename files
        run: 'mv ./build/libs/amber-$version.jar ./build/libs/amber-$version+$commithash.jar && mv ./build/libs/amber-$version-sources.jar ./build/libs/amber-$version+$commithash-sources.jar'
      - name: Release
        run: 'hub release create -p -a ./build/libs/amber-$version+$commithash.jar -a ./build/libs/amber-$version+$commithash-sources.jar -F RELEASE_NOTE.md $version+$commithash'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  qodana:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          linter: jetbrains/qodana-jvm
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          publish_branch: gh-pages
          destination_dir: ./qodana
  dokka:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: Dokka Build
        run: './gradlew dokkaHtml'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
          publish_branch: gh-pages
          destination_dir: ./dokka
