name: Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[nobuild]')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: Download Assets
        run: './gradlew downloadAssets'
      - name: Generate Sources
        run: './gradlew genSources'
      - name: Build with Gradle
        run: './gradlew build'
      - name: Get version
        run: 'echo "VERSION=$(./gradlew -q getVersionName)" >> $GITHUB_ENV'
      - name: Get commit hash
        run: 'echo "COMMIT_HASH=$(echo $GITHUB_SHA | head -c 12)" >> $GITHUB_ENV'
      - name: Set Release Note Version
        run: 'sed -i "s/{{ VERSION }}/${{ env.VERSION }}/" RELEASE_NOTE.md'
      - name: Set Release Note Commit Hash
        run: 'sed -i "s/{{ COMMIT_HASH }}/${{ env.COMMIT_HASH }}/" RELEASE_NOTE.md'
      - name: Set Release Note Build Number
        run: 'sed -i "s/{{ BUILD_NUMBER }}/-$GITHUB_RUN_NUMBER/" RELEASE_NOTE.md'
      - name: Set Release Note Message
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{ COMMIT_MESSAGE }}"
          replace: ${{ github.event.head_commit.message }}
          include: 'RELEASE_NOTE.md'
          regex: false
      - name: Rename files
        run: |
          mv ./build/libs/amber-${{ env.VERSION }}.jar ./build/libs/amber-${{ env.VERSION }}-$GITHUB_RUN_NUMBER+${{ env.COMMIT_HASH }}.jar
          mv ./build/libs/amber-${{ env.VERSION }}-sources.jar ./build/libs/amber-${{ env.VERSION }}-$GITHUB_RUN_NUMBER+${{ env.COMMIT_HASH }}-sources.jar
      - name: Release
        run: 'hub release create -p -a ./build/libs/amber-${{ env.VERSION }}-$GITHUB_RUN_NUMBER+${{ env.COMMIT_HASH }}.jar -a ./build/libs/amber-${{ env.VERSION }}-$GITHUB_RUN_NUMBER+${{ env.COMMIT_HASH }}-sources.jar -F RELEASE_NOTE.md ${{ env.VERSION }}-$GITHUB_RUN_NUMBER+${{ env.COMMIT_HASH }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: './gradlew publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_STRING: ${{ env.VERSION }}-${{ github.run_number }}+${{ env.COMMIT_HASH }}
  qodana:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          linter: jetbrains/qodana-jvm
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          publish_branch: gh-pages
          destination_dir: ./qodana
  dokka:
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: Dokka Build
        run: './gradlew dokkaHtml'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/html
          publish_branch: gh-pages
          destination_dir: ./dokka
