name: Release

on:
  workflow_dispatch:
    inputs:
      releaseNote:
        description: 'The release note'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: Download Assets
        run: './gradlew downloadAssets'
      - name: Generate Sources
        run: './gradlew genSources'
      - name: Build with Gradle
        run: './gradlew build'
      - name: Get version
        run: 'version=$(./gradlew -q getVersionName)'
      - name: Set Release Note Version
        run: 'sed -i "s/{{ VERSION }}/$version/" RELEASE_NOTE.md'
      - name: Set Release Note Commit Hash
        run: 'sed -i "s/{{ COMMIT_HASH }}/final/" RELEASE_NOTE.md'
      - name: Set Release Note Message
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{ COMMIT_MESSAGE }}"
          replace: ${{ github.event.inputs.releaseNote }}
          include: 'RELEASE_NOTE.md'
          regex: false
      - name: Rename files
        run: 'mv ./build/libs/amber-$version.jar ./build/libs/amber-$version+final.jar && mv ./build/libs/amber-$version-sources.jar ./build/libs/amber-$version+final-sources.jar'
      - name: Release
        run: 'hub release create -a ./build/libs/amber-$version+final.jar -a ./build/libs/amber-$version+final-sources.jar -F RELEASE_NOTE.md $version+final'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
