name: Release

on:
  workflow_dispatch:
    inputs:
      releaseNote:
        description: 'The release note'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup
        run: 'chmod +x ./gradlew'
      - name: Download Assets
        run: './gradlew downloadAssets'
      - name: Generate Sources
        run: './gradlew genSources'
      - name: Build with Gradle
        run: './gradlew build'
      - name: Get version
        run: 'echo "VERSION=$(./gradlew -q getVersionName)" >> $GITHUB_ENV'
      - name: Get commit hash
        run: 'echo "COMMIT_HASH=$(echo $GITHUB_SHA | head -c 12)" >> $GITHUB_ENV'
      - name: Set Release Note Version
        run: 'sed -i "s/{{ VERSION }}/${{ env.VERSION }}/" RELEASE_NOTE.md'
      - name: Set Release Note Commit Hash
        run: 'sed -i "s/{{ COMMIT_HASH }}/${{ env.COMMIT_HASH }}/" RELEASE_NOTE.md'
      - name: Set Release Note Build Number
        run: 'sed -i "s/{{ BUILD_NUMBER }}//" RELEASE_NOTE.md'
      - name: Set Release Note Message
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{ COMMIT_MESSAGE }}"
          replace: ${{ github.event.inputs.releaseNote }}
          include: 'RELEASE_NOTE.md'
          regex: false
      - name: Rename files
        run: |
          mv ./build/libs/amber-${{ env.VERSION }}.jar ./build/libs/amber-${{ env.VERSION }}+${{ env.COMMIT_HASH }}.jar
          mv ./build/libs/amber-${{ env.VERSION }}-sources.jar ./build/libs/amber-${{ env.VERSION }}+${{ env.COMMIT_HASH }}-sources.jar
      - name: Release
        run: 'hub release create -a ./build/libs/amber-${{ env.VERSION }}+${{ env.COMMIT_HASH }}.jar -a ./build/libs/amber-${{ env.VERSION }}+${{ env.COMMIT_HASH }}-sources.jar -F RELEASE_NOTE.md ${{ env.VERSION }}+${{ env.COMMIT_HASH }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: './gradlew publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_STRING: ${{ env.VERSION }}+${{ env.COMMIT_HASH }}
